.PHONY: clean

# Remove root-level executables generated by builds but keep the sources and Makefile.
clean:
	find . -maxdepth 1 -type f -perm /111 ! -name "Makefile" ! -name ".gitignore" ! -name "*.c" -exec rm -f -- "{}" +
